// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8df12aa3-7fc2-4fc7-80cc-dcca44c9c992";

const char SSID[]        = "DavidRiz";    // Network SSID (name)
const char PASS[]        = "HURUF KECIL SEMUA";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "xNY3QI9CYdenBVsOS1d9DMaZU";    // Secret device password

void onThermalChange();
void onFanChange();

float thermal;
bool fan;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(thermal, READWRITE, ON_CHANGE, onThermalChange);
  ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
